In [1]:
import pandas as pd

In [2]:
file="resources/JC-202104-citibike-tripdata.csv"

df=pd.read_csv(file)
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1900,2021-04-01 00:07:25.4780,2021-04-01 00:39:06.0800,3225,Baldwin at Montgomery,40.723659,-74.064194,3225,Baldwin at Montgomery,40.723659,-74.064194,45464,Customer,1970,0
1,236,2021-04-01 00:08:13.9440,2021-04-01 00:12:10.1330,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,38392,Customer,1970,0
2,1047,2021-04-01 00:11:01.4250,2021-04-01 00:28:28.5300,3276,Marin Light Rail,40.714584,-74.042817,3678,Fairmount Ave,40.725726,-74.071959,54268,Customer,1970,0
3,491,2021-04-01 00:15:09.7010,2021-04-01 00:23:20.8380,3202,Newport PATH,40.727224,-74.033759,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,42307,Customer,1970,0
4,193,2021-04-01 00:21:05.0750,2021-04-01 00:24:18.2960,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44452,Customer,1970,0

In [3]:
df.count()

tripduration               23318
starttime                  23318
stoptime                   23318
start station id           23318
start station name         23318
start station latitude     23318
start station longitude    23318
end station id             23318
end station name           23318
end station latitude       23318
end station longitude      23318
bikeid                     23318
usertype                   23318
birth year                 23318
gender                     23318
dtype: int64

In [4]:
df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [5]:
df.isnull().any().any()

False

In [6]:
df=df.drop_duplicates()
df.count()

tripduration               23318
starttime                  23318
stoptime                   23318
start station id           23318
start station name         23318
start station latitude     23318
start station longitude    23318
end station id             23318
end station name           23318
end station latitude       23318
end station longitude      23318
bikeid                     23318
usertype                   23318
birth year                 23318
gender                     23318
dtype: int64

In [7]:
df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1900,2021-04-01 00:07:25.4780,2021-04-01 00:39:06.0800,3225,Baldwin at Montgomery,40.723659,-74.064194,3225,Baldwin at Montgomery,40.723659,-74.064194,45464,Customer,1970,0
1,236,2021-04-01 00:08:13.9440,2021-04-01 00:12:10.1330,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,38392,Customer,1970,0
2,1047,2021-04-01 00:11:01.4250,2021-04-01 00:28:28.5300,3276,Marin Light Rail,40.714584,-74.042817,3678,Fairmount Ave,40.725726,-74.071959,54268,Customer,1970,0
3,491,2021-04-01 00:15:09.7010,2021-04-01 00:23:20.8380,3202,Newport PATH,40.727224,-74.033759,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,42307,Customer,1970,0
4,193,2021-04-01 00:21:05.0750,2021-04-01 00:24:18.2960,3195,Sip Ave,40.730897,-74.063913,3194,McGinley Square,40.725340,-74.067622,44452,Customer,1970,0

In [38]:
# if start and end are the same station, filter
filter_df=df.loc[:, 'start station id']==df['end station id']
repeat_df=df.loc[filter_df, :]
repeat_df.count()

tripduration               3374
starttime                  3374
stoptime                   3374
start station id           3374
start station name         3374
start station latitude     3374
start station longitude    3374
end station id             3374
end station name           3374
end station latitude       3374
end station longitude      3374
bikeid                     3374
usertype                   3374
birth year                 3374
gender                     3374
dtype: int64

In [21]:
repeat_df.sort_values(['tripduration'], ascending=True).head(20)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1770,61,2021-04-04 16:14:06.9160,2021-04-04 16:15:08.3760,3184,Paulus Hook,40.714145,-74.033552,3184,Paulus Hook,40.714145,-74.033552,46472,Customer,1970,0
15746,61,2021-04-22 20:31:15.9400,2021-04-22 20:32:17.6600,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,46382,Customer,1970,0
20279,61,2021-04-27 21:51:52.4040,2021-04-27 21:52:53.8740,3276,Marin Light Rail,40.714584,-74.042817,3276,Marin Light Rail,40.714584,-74.042817,54254,Customer,1970,0
21173,62,2021-04-28 20:22:30.7870,2021-04-28 20:23:33.6680,3639,Harborside,40.719252,-74.034234,3639,Harborside,40.719252,-74.034234,17231,Customer,1970,0
21656,63,2021-04-28 23:42:10.6480,2021-04-28 23:43:14.3730,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,54269,Customer,1970,0
2123,65,2021-04-04 20:00:12.9780,2021-04-04 20:01:18.6850,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,18808,Customer,1970,0
9819,65,2021-04-14 21:09:07.6300,2021-04-14 21:10:13.0020,3483,Montgomery St,40.719420,-74.050990,3483,Montgomery St,40.719420,-74.050990,42450,Customer,1970,0
4096,66,2021-04-06 23:06:46.6040,2021-04-06 23:07:53.5040,3195,Sip Ave,40.730897,-74.063913,3195,Sip Ave,40.730897,-74.063913,54264,Customer,1970,0
20208,66,2021-04-27 20:49:01.2970,2021-04-27 20:50:07.8650,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,45499,Customer,1970,0
7523,66,2021-04-10 20:53:50.6940,2021-04-10 20:54:57.4720,3203,Hamilton Park,40.727596,-74.044247,3203,Hamilton Park,40.727596,-74.044247,38139,Customer,1970,0
1819,66,2021-04-04 17:00:17.9520,2021-04-04 17:01:23.9970,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,44576,Customer,1970,0
9677,67,2021-04-14 18:18:55.3630,2021-04-14 18:20:02.7630,3195,Sip Ave,40.730897,-74.063913,3195,Sip Ave,40.730897,-74.063913,38533,Customer,1970,0
9155,68,2021-04-13 23:25:55.6630,2021-04-13 23:27:04.6310,3270,Jersey & 6th St,40.725289,-74.045572,3270,Jersey & 6th St,40.725289,-74.045572,48932,Customer,1970,0
2144,69,2021-04-04 20:09:03.7420,2021-04-04 20:10:13.5280,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,45354,Customer,1970,0
11587,69,2021-04-17 19:57:05.4260,2021-04-17 19:58:14.5810,3203,Hamilton Park,40.727596,-74.044247,3203,Hamilton Park,40.727596,-74.044247,26664,Customer,1970,0
17756,69,2021-04-24 20:24:54.7370,2021-04-24 20:26:03.8530,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,49081,Customer,1970,0
17277,69,2021-04-24 16:18:45.9810,2021-04-24 16:19:55.7180,3276,Marin Light Rail,40.714584,-74.042817,3276,Marin Light Rail,40.714584,-74.042817,42343,Customer,1970,0
13600,69,2021-04-19 23:42:25.5490,2021-04-19 23:43:35.2850,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,39407,Customer,1970,0
3713,70,2021-04-06 18:52:03.9040,2021-04-06 18:53:14.2460,3195,Sip Ave,40.730897,-74.063913,3195,Sip Ave,40.730897,-74.063913,40958,Customer,1970,0
3963,70,2021-04-06 22:03:40.5640,2021-04-06 22:04:50.6780,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,47255,Customer,1970,0

In [29]:
# filter where tripduration < 120 seconds
filter_time_df=repeat_df.loc[:, 'tripduration']<120
short_df=repeat_df.loc[filter_time_df, :]
short_df.count()

tripduration               107
starttime                  107
stoptime                   107
start station id           107
start station name         107
start station latitude     107
start station longitude    107
end station id             107
end station name           107
end station latitude       107
end station longitude      107
bikeid                     107
usertype                   107
birth year                 107
gender                     107
dtype: int64

In [28]:
short_df.sort_values(['tripduration'])

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
20279,61,2021-04-27 21:51:52.4040,2021-04-27 21:52:53.8740,3276,Marin Light Rail,40.714584,-74.042817,3276,Marin Light Rail,40.714584,-74.042817,54254,Customer,1970,0
15746,61,2021-04-22 20:31:15.9400,2021-04-22 20:32:17.6600,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,46382,Customer,1970,0
1770,61,2021-04-04 16:14:06.9160,2021-04-04 16:15:08.3760,3184,Paulus Hook,40.714145,-74.033552,3184,Paulus Hook,40.714145,-74.033552,46472,Customer,1970,0
21173,62,2021-04-28 20:22:30.7870,2021-04-28 20:23:33.6680,3639,Harborside,40.719252,-74.034234,3639,Harborside,40.719252,-74.034234,17231,Customer,1970,0
21656,63,2021-04-28 23:42:10.6480,2021-04-28 23:43:14.3730,3192,Liberty Light Rail,40.711242,-74.055701,3192,Liberty Light Rail,40.711242,-74.055701,54269,Customer,1970,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14896,176,2021-04-21 14:18:27.7910,2021-04-21 14:21:24.4520,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,44316,Customer,1970,0
16141,176,2021-04-23 15:35:49.8100,2021-04-23 15:38:46.0030,3638,Washington St,40.724294,-74.035483,3638,Washington St,40.724294,-74.035483,31092,Customer,1970,0
730,177,2021-04-02 20:37:50.4170,2021-04-02 20:40:47.4320,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,25971,Customer,1970,0
17812,178,2021-04-24 20:54:18.6010,2021-04-24 20:57:16.7070,3185,City Hall,40.717733,-74.043845,3185,City Hall,40.717733,-74.043845,32349,Customer,1970,0
7033,179,2021-04-10 16:17:37.1190,2021-04-10 16:20:36.9360,3202,Newport PATH,40.727224,-74.033759,3202,Newport PATH,40.727224,-74.033759,32095,Customer,1970,0

In [36]:
filter_1=df.loc[:, 'start station id']!=df['end station id']
filter_2=df.loc[:, 'tripduration']>120
new_df=df.loc[filter_1 & filter_2, :]
new_df.count()

tripduration               19513
starttime                  19513
stoptime                   19513
start station id           19513
start station name         19513
start station latitude     19513
start station longitude    19513
end station id             19513
end station name           19513
end station latitude       19513
end station longitude      19513
bikeid                     19513
usertype                   19513
birth year                 19513
gender                     19513
dtype: int64

In [37]:
# write to csv
new_df.to_csv('resources/april_2021_clean.csv', index=False, header=True)